---
- hosts: all
  vars:
    username: vagrant
  tasks:
    - include: ./tasks/base.yml
    - include: ./tasks/git.yml
    # - include: ./tasks/nodejs_4.x.yml
    - include: ./tasks/nodejs_6.x.yml
    - include: ./tasks/nvm.yml
    - include: ./tasks/vim-pathogen.yml
    - include: ./tasks/vim-theme-atom-dark.yml
    - include: ./tasks/vim.yml
    - include: ./tasks/dos2unix.yml
    - include: ./tasks/oraclejdk8.yml
    # - include: ./tasks/openjdk8.yml
    - include: ./tasks/inotifylimit.yml
    - include: ./tasks/docker-engine.yml
    - include: ./tasks/docker-compose.yml
    
